### ISSUE TITLE
Is there any alternative for net core?

### ISSUE THREAD

**Issue by adriangodoy** [MicrosoftDocs/visualstudio-docs.es-es#19]
As this doesn't work for net core and I find this diagrams really useful and I would like to be able to use them.  What's the point on enterprise version if you can't use it's functions for latest technologies?  

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 6a25a17b-a48c-f9f1-f61e-6b3e1479a199
* Version Independent ID: 3ccc0a49-c4d3-8c92-1b11-81a4198441d3
* Content: [Validación código con diagramas de dependencia - Visual Studio](https://docs.microsoft.com/es-es/visualstudio/modeling/validate-code-with-layer-diagrams?view=vs-2017)
* Content Source: [docs/modeling/validate-code-with-layer-diagrams.md](https://github.com/MicrosoftDocs/visualstudio-docs.es-es/blob/live/docs/modeling/validate-code-with-layer-diagrams.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by CeciAc** [comment]
Hello, @adriangodoy 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
