### ISSUE TITLE
'a' de más

### ISSUE THREAD

**Issue by luis-flores** [MicrosoftDocs/visualstudio-docs.es-es#21]
Me parece que en la sección "Seguridad de acceso del código de ClickOnce predeterminada", la frase: 
"esto permite que a la aplicación (y el sistema del usuario final) sea susceptible a un ataque de software malintencionado" 
debería leerse de la siguiente manera: 
"esto permite que la aplicación (y el sistema del usuario final) sea susceptible a un ataque de software malintencionado", 
sin la 'a' que sigue al 'que'.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 38670706-d4d8-6254-7ef7-7330b40855f7
* Version Independent ID: c9390771-eb44-4b17-fdd5-48fa94979ced
* Content: [Seguridad de acceso del código para aplicaciones ClickOnce - Visual Studio](https://docs.microsoft.com/es-es/visualstudio/deployment/code-access-security-for-clickonce-applications?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DES-ES%26k%3Dk(vb.ProjectPropertiesSecurity.HowTo)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.5)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/deployment/code-access-security-for-clickonce-applications.md](https://github.com/MicrosoftDocs/visualstudio-docs.es-es/blob/live/docs/deployment/code-access-security-for-clickonce-applications.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by CeciAc** [comment]
Hola, @luis-flores 

Gracias por sus comentarios. 

Los revisaremos y nos pondremos en contacto con usted lo antes posible. 

Atentamente, 
Equipo internacional de Microsoft Docs

**Comment by CeciAc** [comment]
Hola, @luis-flores

Gracias por sus comentarios. 

El equipo lingüístico ha revisado las sugerencias y las ha aceptado. Hemos implementado sus comentarios y los hemos publicado en los artículos actualizados del sitio de Docs en las siguientes páginas: https://docs.microsoft.com/es-es/visualstudio/deployment/code-access-security-for-clickonce-applications?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DES-ES%26k%3Dk(vb.ProjectPropertiesSecurity.HowTo)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.5)%26rd%3Dtrue&view=vs-2019 

Apreciamos su colaboración y le animamos a seguir enviándonos comentarios. 

Atentamente, 
Equipo internacional de Microsoft Docs
