### ISSUE TITLE
Excelente inicio

### ISSUE THREAD

**Issue by KCS-DEV-TEAM** [MicrosoftDocs/visualstudio-docs.es-es#22]
Para todo aquel que no conoce el IDE de visual studio es un comienzo obligado

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: aa3004b2-f05f-11a0-02e9-2ccf463e9c39
* Version Independent ID: 5e8622e6-b24b-e95c-9bf7-648c48d4998a
* Content: [Información general de Visual Studio para desarrolladores de Python](https://docs.microsoft.com/es-es/visualstudio/python/visual-studio-ide?view=vs-2019#feedback)
* Content Source: [docs/python/visual-studio-ide.md](https://github.com/MicrosoftDocs/visualstudio-docs.es-es/blob/live/docs/python/visual-studio-ide.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by CeciAc** [comment]
Hola, @KCS-DEV-TEAM

Apreciamos enormemente sus comentarios. Nos complace comprobar que su experiencia con la documentación cumple con sus expectativas. 

Le recomendamos que proporcione comentarios para que podamos seguir mejorando su experiencia. 

Atentamente, 
Equipo internacional de Microsoft Docs
