### ISSUE TITLE
Is it always an evitable violation?

### ISSUE THREAD

**Issue by fermatkepler** [MicrosoftDocs/visualstudio-docs.es-es#25]
Example: Let FmRoles be
    public class FmRoles
    {
        public static int DirectoryType { get; set; } = 1;
        public static string Admins { get; set; }
        public static string Writers { get; set; }
        public static string Readers { get; set; }
    }

What if I want to configure a class in Startup() as below?

            var configSection = Configuration.GetSection("Groups");
            if (configSection.Exists())       configSection.Get&lt;FmRoles&gt;();

I couldn't do it if marked FmRoles as static

And I think it's a nice way to get the configuration  (maybe I'm wrong) in a useful class. The other way could be using a singleton and 
services.Configure&lt;FmRoles&gt;(Configuration.GetSection("Groups"));

But it's problematic injecting singletons in attributes. Working in the way I do, it's easy to do: 
    internal class AdminAttribute : AuthorizeAttribute
    {
        public AdminAttribute()
        {
            this.Roles = FmRoles.Admins;
        }
    }

Is it a 'best practice' my way of doing? Should be relaxed CA1052? Maybe more permissible  configSection.Get&lt;StaticClass&gt;();?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 42f04bd3-010f-c948-6098-008ec722be9c
* Version Independent ID: 3ef62cfb-b3b8-c5d7-3f7c-9e9032178dd0
* Content: [CA1052: Los tipos de titulares estáticos deben ser estáticos o NotInheritable - Visual Studio](https://docs.microsoft.com/es-es/visualstudio/code-quality/ca1052-static-holder-types-should-be-sealed?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca1052-static-holder-types-should-be-sealed.md](https://github.com/MicrosoftDocs/visualstudio-docs.es-es/blob/live/docs/code-quality/ca1052-static-holder-types-should-be-sealed.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by srvbpigh** [comment]
Hello, @fermatkepler
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello, @fermatkepler ,

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.

We truly appreciate your contribution to our articles.

Microsoft DOCS International Team
