### ISSUE TITLE
Lenguaje R Not Work in visual studio 2019 

### ISSUE THREAD

**Issue by andresgarcia0313** [MicrosoftDocs/visualstudio-docs.es-es#37]
[Escriba sus comentarios aquí]

Lenguaje R Not Work in visual studio 2019 

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: dde63717-000d-d97c-0898-36c005d8541f
* Version Independent ID: 4c63fc76-7fac-4e58-cca7-e8476cb1248f
* Content: [Tutorial de introducción a R - Visual Studio](https://docs.microsoft.com/es-es/visualstudio/rtvs/getting-started-with-r?view=vs-2017&viewFallbackFrom=vs-2019)
* Content Source: [docs/rtvs/getting-started-with-r.md](https://github.com/MicrosoftDocs/visualstudio-docs.es-es/blob/live/docs/rtvs/getting-started-with-r.md)
* Product: **visual-studio-dev15**
* Technology: **vs-rtvs**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Yes, unfortunately R support was dropped from Visual Studio 2019. That is why there is no documentation for VS 2019 and the R language.

**Comment by andresgarcia0313** [comment]
it would be possible to add a sign that it is not available for 2019 or, failing that, in the documentation, it does not allow to see that in the 2019 documentation, because it implies that if it exists

**Comment by kraigb** [comment]
There's an automatic indicator at the top of the page that the content isn't available for VS 2019. It then opens the 2017 page. This behavior is by design, and because the 2017 content is archived we're not making updates.
