### ISSUE TITLE
Problemas al instalar

### ISSUE THREAD

**Issue by soloyose1234** [MicrosoftDocs/visualstudio-docs.es-es#38]
[Tengo problemas al instalar el visual studio community ya que hay un error al momento de cargar el instalador deja de funcionar y no habre el menú de lo componentes]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 2a3b0ef4-76d9-9c1e-4625-9cd56689b43a
* Version Independent ID: e882e8dc-8fb1-231d-d0bb-1f3e9dfec90d
* Content: [Quitar Visual Studio](https://docs.microsoft.com/es-es/visualstudio/install/remove-visual-studio?view=vs-2019)
* Content Source: [docs/install/remove-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.es-es/blob/live/docs/install/remove-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by JasonCard** [comment]
@soloyose1234 Please report your problem to [https://developercommunity.visualstudio.com/spaces/8/index.html](https://developercommunity.visualstudio.com/spaces/8/index.html).
